services:
  dingdong:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    volumes:
      - dingdong_data:/app/pb_data
    restart: unless-stopped
    environment:
      - TZ=UTC
    # healthcheck:
    #   test:
    #     [
    #       "CMD",
    #       "wget",
    #       "--no-verbose",
    #       "--tries=1",
    #       "--spider",
    #       "http://localhost:8090/_/health",
    #     ]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s

volumes:
  dingdong_data:

